[versions] # version numbers
agp = "8.13.0"                  # Android Gradle plugin
kotlin = "2.0.21"               # Kotlin version
coreKtx = "1.17.0"              # Core KTX
junit = "4.13.2"                # JUnit test
junitVersion = "1.3.0"          # AndroidX JUnit
espressoCore = "3.7.0"          # Espresso test
lifecycleRuntimeKtx = "2.9.3"   # Lifecycle runtime
activityCompose = "1.10.1"      # Activity Compose
composeBom = "2025.08.01"       # Compose BOM
navigationCompose = "2.9.3"     # Navigation Compose
lifecycleViewmodelCompose = "2.9.3" # ViewModel Compose
androidPdfViewerMhiew = "3.2.0-beta.3" # PDF viewer
appcompat = "1.7.1"             # AppCompat support
coreLibraryDesugaring = "2.1.5" # Java desugaring
fragmentKtx = "1.8.9"           # Fragment KTX
material = "1.13.0"             # Google Material
materialIconsExtended = "1.7.8" # Extra Material icons
room = "2.6.1"                  # Room database
ksp = "2.0.21-1.0.25"           # KSP plugin
gson = "2.10.1"                 # GSON JSON PARSER
foundationLayout = "1.9.3"      # Foundation Layout
splashscreen = "1.0.1"          # SPLASH Screen
datastore = "1.0.0"             # Data Store

[libraries] # dependency list
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" } # Core KTX
junit = { group = "junit", name = "junit", version.ref = "junit" } # JUnit
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" } # AndroidX JUnit
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" } # Espresso
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" } # Lifecycle runtime
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" } # Compose activity
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" } # Compose BOM
androidx-ui = { group = "androidx.compose.ui", name = "ui" } # Compose UI
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" } # Compose graphics
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } # Compose tooling
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" } # UI preview
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" } # Test manifest
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" } # UI JUnit test
androidx-material3 = { group = "androidx.compose.material3", name = "material3" } # Material3
androidx-core-splashscreen  = {group = 'androidx.core', name='core-splashscreen', version.ref='splashscreen'} # Splash Screen
androidx-datastore-preferences = {group = 'androidx.datastore', name='datastore-preferences', version.ref='datastore'} # Data Store



# Extra libraries
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" } # AppCompat
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" } # Fragment KTX
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" } # ViewModel Compose
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" } # Material icons
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" } # Navigation Compose
android-pdf-viewer-mhiew = { group = "com.github.mhiew", name = "android-pdf-viewer", version.ref = "androidPdfViewerMhiew" } # PDF viewer
tools-desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "coreLibraryDesugaring" } # Java desugaring
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" } # Google Material

# Room database
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" } # Room runtime
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" } # Room KTX
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" } # Room compiler

#JSON parser
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" } # JSON parser (convert objects)

[plugins] # Gradle plugins
android-application = { id = "com.android.application", version.ref = "agp" } # Android app plugin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" } # Kotlin Android
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" } # Compose plugin
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" } # KSP plugin
